language: node_js
node_js:
  - '8'
  - '10'
  - 'node'
matrix:
  fast_finish: true
  allow_failures:
    # v11.11 is broken with Jest
    - node_js: 'node'
before_script:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH
  - yarn install --frozen-lockfile
  - yarn run setup
script:
  - yarn test
  - yarn run test:int:pass
  - yarn run test:int:fail
notifications:
  email: false
cache:
  yarn: true
